language: node_js
node_js:
-'v8.0.0'
env:
     -DB=postgresql://postgres@localhost:5432/greet_test

 
before_script:
        -psql -c 'create database greet_test;' -U postgres
         -psql -U postgres -d greet_test -a -f greet.sql
  addons:
    apt:
      packages:
        -postgres-server-dev-9.2       
